import { db } from "@/db";
import { vendors } from "@/db/schema/schema";

const seedData = [
    {
        supplier: "2000000",
        nameOfVendor: "Michelin Asia Co. Pte. Ltd.",
        street: "77, Robinson Road #34-01 & #35-01,",
        country: "SG",
        postalCode: "068896",
        city: "Singapore",
        accountGroup: "NCAD",
        searchTerm: "MICHELIN",
        purchOrganization: "2000",
        purchOrgDescr: "Chitra (Central)",
        termsOfPayment: "0014",
        incoterms: "CFR",
        minimumOrderValue: "0.00",
        orderCurrency: "USD",
        salesperson: "Joyce Lim / Jennifer Khor",
        telephone: "",
        numPurchasingOrgs: 1,
        status: "Active",
    },
    {
        supplier: "2000001",
        nameOfVendor: "PT REMA TIP TOP INDONESIA",
        street: "Jl. Taman Sari Raya No. 56 56MD",
        country: "ID",
        postalCode: "11150",
        city: "Jakarta Barat",
        accountGroup: "NCAD",
        searchTerm: "REMA",
        purchOrganization: "2000",
        purchOrgDescr: "Chitra (Central)",
        termsOfPayment: "0015",
        incoterms: "",
        minimumOrderValue: "0.00",
        orderCurrency: "USD",
        salesperson: "Rica Cahyadi",
        telephone: "",
        numPurchasingOrgs: 1,
        status: "Active",
    },
    {
        supplier: "2000002",
        nameOfVendor: "Anda International Pte. Ltd.",
        street: "01-536 Blk 4016, Ang Mo Kio Industr",
        country: "SG",
        postalCode: "203600",
        city: "Singapore",
        accountGroup: "NCAD",
        searchTerm: "ANDA",
        purchOrganization: "2000",
        purchOrgDescr: "Chitra (Central)",
        termsOfPayment: "0015",
        incoterms: "",
        minimumOrderValue: "0.00",
        orderCurrency: "USD",
        salesperson: "",
        telephone: "",
        numPurchasingOrgs: 1,
        status: "Active",
    },
    {
        supplier: "2000003",
        nameOfVendor: "Haltec Corporation",
        street: "Unit 3, 89 Jijaws Street",
        country: "AU",
        postalCode: "4074",
        city: "Summer Park Qld",
        accountGroup: "NCAD",
        searchTerm: "HALTEC",
        purchOrganization: "2000",
        purchOrgDescr: "Chitra (Central)",
        termsOfPayment: "0015",
        incoterms: "CIF",
        minimumOrderValue: "0.00",
        orderCurrency: "USD",
        salesperson: "Peter Moore",
        telephone: "",
        numPurchasingOrgs: 1,
        status: "Active",
    },
    {
        supplier: "2000004",
        nameOfVendor: "Italmatic Tyre & Retreading Equipme",
        street: "362 Upper Paya Lebar Road, #01-11",
        country: "SG",
        postalCode: "534963",
        city: "Da Jin Factory Building",
        accountGroup: "NCAD",
        searchTerm: "ITALMATIC",
        purchOrganization: "2000",
        purchOrgDescr: "Chitra (Central)",
        termsOfPayment: "0001",
        incoterms: "",
        minimumOrderValue: "0.00",
        orderCurrency: "USD",
        salesperson: "Lily Yeo",
        telephone: "",
        numPurchasingOrgs: 1,
        status: "Active",
    },
    {
        supplier: "2000005",
        nameOfVendor: "KANTOR PELAYANAN PAJAK",
        street: "Jl. TMP Kalibata",
        country: "ID",
        postalCode: "12760",
        city: "Jakarta Selatan",
        accountGroup: "NCAD",
        searchTerm: "PAJAK",
        purchOrganization: "2000",
        purchOrgDescr: "Chitra (Central)",
        termsOfPayment: "",
        incoterms: "",
        minimumOrderValue: "0.00",
        orderCurrency: "IDR",
        salesperson: "",
        telephone: "",
        numPurchasingOrgs: 1,
        status: "Pending Audit",
    },
    {
        supplier: "2000006",
        nameOfVendor: "Matec",
        street: "24 Bis, Allee Louis Breguet",
        country: "FR",
        postalCode: "93421",
        city: "Villepinte Cedex",
        accountGroup: "NCAD",
        searchTerm: "MATEC",
        purchOrganization: "2000",
        purchOrgDescr: "Chitra (Central)",
        termsOfPayment: "0015",
        incoterms: "",
        minimumOrderValue: "0.00",
        orderCurrency: "EUR",
        salesperson: "Pierre Antraigue",
        telephone: "",
        numPurchasingOrgs: 1,
        status: "Archived",
    },
];

async function main() {
    console.log("Seeding vendors master data...");
    try {
        for (const data of seedData) {
            await db.insert(vendors).values(data).onConflictDoUpdate({
                target: vendors.supplier,
                set: data,
            });
        }
        console.log("Vendor seeding SUCCESSFUL!");
    } catch (err) {
        console.error("Seeding failed:", err);
    }
}

main();
